version: "3"

services:
  shopdb:
    image: postgres
    container_name: shopdb
    restart: always
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=fullstack123
      - POSTGRES_DB=shopdb
    ports:
      - 5432:5432
    volumes:
      - dbdata:/var/lib/postgresql/data

volumes:
  dbdata:
